x=int(input('Enter number 1: '))
y=int(input('Enter number 2: '))
x=int(x)
y=int(y)
a=str(x+y)
b=str(x-y)
c=str(x*y)
d=str(x%y)
print("The addition of given number is: " + a)
print("The subtraction of given number is: " + b)
print("The multiplication of given number is: " + c)
print("The division of given number is: " + d)